name: Linting workflow
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install yarn
        run: npm install yarn --global
      - name: install modules
        run: yarn install
      - name: lint
        run: yarn run lint
